{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "k8s-pod-visualizer.namespace" . }}
  labels:
    {{- include "k8s-pod-visualizer.labels" . | nindent 4 }}
{{- end }}
